// console.log(date())
let alldate=new Date()
let hh=alldate.getHours()
let mm=alldate.getMinutes()
let ss=alldate.getSeconds()
let dd=alldate.getDay()
let mon=alldate.getMonth()
let yy=alldate.getFullYear()
let ms=alldate.getMilliseconds()
let dy=alldate.getDay()
console.log(hh,mm,ss,dd,mon,yy,ms,dy)